### ISSUE TITLE
如何提交修改pr

### ISSUE THREAD

**Issue by hellohelen222** [Louis-J/HUILV#14]
mac系统中使用git时先fork，然后使用终端克隆，使用git remove -v建立本地与远程仓库的连接，再使用git add . git commit等命令修改文件，增添文件夹，最后push到本地仓库，再pull request

**Comment by susanneli** [comment]
windows装好git后，在想克隆的地方直接右键选git bash，再进行后续操作即可。

**Comment by cbyy3** [comment]
记录一个我在提交修改pr过程中曾经出现的问题：如果用户名和邮箱没有设置好，会导致git commit失败，设置的方法是git config --global user.name "**"、git config --global user.email "**"
